### ISSUE TITLE
infinite scrollable cell is not scrolling

### ISSUE THREAD

**Issue by pvsantosh** [daria-kopaliani/DARecycledScrollView#2]
the infinite scrollable cell is not at all scrollable. need to look into this issue.

**Comment by daria-kopaliani** [comment]
Can you describe the problem you are experiencing in more details?
Not sure what you mean by "the infinite scrollable cell". Cells are not supposed to be scrollable, they are just subviews of a scrollView, which is scrollable if combined width of its tiles is larger than its own width.
