### ISSUE TITLE
Resizing Images

### ISSUE THREAD

**Issue by summerbean** [daria-kopaliani/DARecycledScrollView#3]
Hi Daria, 
Firstly, I'd like to thank you for sharing such a wonderful code with the world! I was just wondering if you could recommend a way to automatically resize images to fit into the cells? 
Many thanks,
Matthew

**Comment by daria-kopaliani** [comment]
Hi Matthew, I'm glad DARecycledScrollView is helpful.
You probably want to subclass DARecycledTileView and add an UIImageView property (see DAImageTileView in the demo project). Then you can set the proper content mode for the imageView, i.e:

```
self.imageView.contentMode = UIViewContentModeScaleAspectFit; 
```
